"""init

Revision ID: 001
Revises:
Create Date: 2024-07-19 14:18:35.539223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData

from bot.database.models import Base
# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    meta: MetaData = Base.metadata
    meta.create_all(bind=bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    meta: MetaData = Base.metadata
    meta.drop_all(bind=bind)
    # ### end Alembic commands ###
